
export const START_TIME_TYPE = {
    STSRT_TEN: 1,
    START_ELEVEN: 2,
    START_TWELVE: 3,
    START_THIRTEEN: 4,
    START_FOURTEEN: 5,
    START_FIFTEEN: 6,
    START_SIXTEEN: 7,
    START_SEVENTEEN: 8,
    START_EIGHTEEN: 9,
    START_NINETEEN : 10,
    START_TWENTY : 11,
    START_TWENTY_ONE : 12,
    START_TWENTY_TWO : 13
};

export const START_TIME_TYPE_TEXT = {
    [START_TIME_TYPE.STSRT_TEN]: '10:00',
    [START_TIME_TYPE.START_ELEVEN]: '11:00',
    [START_TIME_TYPE.START_TWELVE]: '12:00',
    [START_TIME_TYPE.START_THIRTEEN]: '13:00',
    [START_TIME_TYPE.START_FOURTEEN]: '14:00',
    [START_TIME_TYPE.START_FIFTEEN]: '15:00',
    [START_TIME_TYPE.START_SIXTEEN]: '16:00',
    [START_TIME_TYPE.START_SEVENTEEN]: '17:00',
    [START_TIME_TYPE.START_EIGHTEEN]: '18:00',
    [START_TIME_TYPE.START_NINETEEN]: '19:00',
    [START_TIME_TYPE.START_TWENTY]: '20:00',
    [START_TIME_TYPE.START_TWENTY_ONE]: '21:00',
    [START_TIME_TYPE.START_TWENTY_TWO]: '22:00',
}