
export const STYLIST_POST_TYPE = {
    NO_POSITION: 0,
    SUB_MANAGER: 1,
    MANAGER: 2,
};

export const STYLIST_POST_TYPE_TEXT = {
    [STYLIST_POST_TYPE.NO_POSITION]: '役職無し',
    [STYLIST_POST_TYPE.SUB_MANAGER]: '副店長',
    [STYLIST_POST_TYPE.MANAGER]: '店長',
}